BMP280_CLI_VERSION = 0.1
BMP280_CLI_LICENSE = MIT
BMP280_CLI_SITE = $(BR2_EXTERNAL_RPI0W_PACKAGES_PATH)/package/bmp280-cli/src
BMP280_CLI_SITE_METHOD = local
BMP280_CLI_LICENSE_FILES = COPYING
BMP280_CLI_INSTALL_TARGET = YES

MESON_CONF_OPTS += --buildtype=debug

define BMP280_CLI_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 \
		$(@D)/build/bmp280-cli $(TARGET_DIR)/usr/bin/bmp280-cli
endef

$(eval $(meson-package))
