RPI0W_LED_USER_VERSION = 0.1
RPI0W_LED_USER_LICENSE = MIT
RPI0W_LED_USER_SITE = $(BR2_EXTERNAL_RPI0W_PACKAGES_PATH)/package/rpi0w-led-user/src
RPI0W_LED_USER_SITE_METHOD = local
RPI0W_LED_USER_LICENSE_FILES = COPYING
RPI0W_LED_USER_INSTALL_TARGET = YES

define RPI0W_LED_USER_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) \
		CC="$(TARGET_CC)" \
		CFLAGS="$(TARGET_CFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS)"
endef

define RPI0W_LED_USER_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/rpi0w-led $(TARGET_DIR)/usr/bin/rpi0w-led
endef

$(eval $(generic-package))
