header:
  version: 14

distro: rpidev
target: rpi-image-dev

repos:
  poky:
    path: layers/poky
    branch: mickledore
    url: https://github.com/yoctoproject/poky.git
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
      meta-selftest:
      meta-skeleton:
  meta-openembedded:
    path: layers/meta-openembedded
    branch: mickledore
    url: https://github.com/openembedded/meta-openembedded.git
    layers:
      meta-oe:
      meta-python:
      meta-multimedia:
      meta-networking:
  meta-raspberrypi:
    path: layers/meta-raspberrypi
    branch: mickledore
    url: https://github.com/agherzan/meta-raspberrypi.git
  meta-raspberrypi-extras:
    path: layers/meta-raspberrypi-extras
    branch: main
    url: https://github.com/agentdenton/meta-raspberrypi-extras.git
  meta-raspberrypi-secrets:
    path: layers/meta-raspberrypi-secrets
    branch: main
    url: git@github.com:agentdenton/meta-raspberrypi-secrets.git

local_conf_header:
  common_flags: |
    PACKAGE_CLASSES = "package_ipk"
