header:
  version: 11

distro: rpidev
target: rpi-image-dev

repos:
  poky:
    url: https://github.com/yoctoproject/poky.git
    refspec: mickledore
    path: layers/poky
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
      meta-selftest:
      meta-skeleton:
  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi.git
    refspec: mickledore
    path: layers/meta-raspberrypi
  meta-raspberrypi-extras:
    path: layers/meta-raspberrypi-extras
    refspec: main
    url: https://github.com/agentdenton/meta-raspberrypi-extras.git

local_conf_header:
  dist-common: |
    PACKAGE_CLASSES = "package_ipk"
