RPI0W_LED_VERSION = 0.1
RPI0W_LED_LICENSE = MIT
RPI0W_LED_SITE = $(TOPDIR)/package/rpi0w-led/src
RPI0W_LED_SITE_METHOD = local
RPI0W_LED_LICENSE_FILES = COPYING
RPI0W_LED_INSTALL_TARGET = YES

define RPI0W_LED_BUILD_CMDS
	$(MAKE) -C $(@D) CC="$(TARGET_CC)" CFLAGS="$(TARGET_CFLAGS)" LDFLAGS="$(TARGET_LDFLAGS)"
endef

define RPI0W_LED_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/rpi0w-led $(TARGET_DIR)/usr/bin/rpi0w-led
endef

$(eval $(generic-package))
